DROP TABLE IF EXISTS FATO_VOO;
DROP TABLE IF EXISTS DIM_AEROPORTO;
DROP TABLE IF EXISTS DIM_DATA;
DROP TABLE IF EXISTS DIM_EMPRESA;
DROP TABLE IF EXISTS DIM_GRUPO_VOO;

CREATE TABLE DIM_EMPRESA
(
    ID_EMPRESA            INT PRIMARY KEY,
    NOME_EMPRESA          VARCHAR(120) NOT NULL,
    NACIONALIDADE_EMPRESA VARCHAR(120) NOT NULL
);


CREATE TABLE DIM_DATA
(
    ID_DATA INT PRIMARY KEY,
    ANO     INT         NOT NULL,
    MES     VARCHAR(45) NOT NULL
    -- TRIMESTRE VARCHAR (45) NOT NULL,
    -- SEMESTRE VARCHAR (45) NOT NULL
    );

CREATE TABLE DIM_AEROPORTO
(
    ID_AEROPORTO         INT PRIMARY KEY,
    SIGLA_AEROPORTO      CHAR(4)      NOT NULL,
    NOME_AEROPORTO       VARCHAR(120) NOT NULL,
    UF_AEROPORTO         CHAR(2)      NULL,
    REGIAO_AEROPORTO     VARCHAR(50)  NULL,
    PAIS_AEROPORTO       VARCHAR(120) NOT NULL,
    CONTINENTE_AEROPORTO VARCHAR(45)  NOT NULL
);

CREATE TABLE DIM_GRUPO_VOO(
  ID_GRUPO_VOO 			INT PRIMARY KEY,
  NOME_GRUPO_VOO 		VARCHAR(45) NOT NULL
);

CREATE TABLE FATO_VOO
(
    ID_DATA              INT NOT NULL,
    ID_EMPRESA           INT NOT NULL,
    ID_AEROPORTO_ORIGEM  INT NOT NULL,
    ID_AEROPORTO_DESTINO INT NOT NULL,
	ID_GRUPO_VOO	     INT NOT NULL,
    NATUREZA             VARCHAR(45),
    PASSAGEIROS_PAGOS    INT,
    PASSAGEIROS_GRATIS   INT,
    CARGA_PAGA_KG        BIGINT,
    CARGA_GRATIS_KG      BIGINT,
    CORREIO_KG           BIGINT,
    ASK                  BIGINT,
    RPK                  BIGINT,
    ATK                  BIGINT,
    RTK                  BIGINT,
    COMBUSTIVEL          BIGINT,
    DISTANCIA_VOADA      BIGINT,
    DECOLAGENS           INT,
    CARGA_PAGA_KM        BIGINT,
    CARGA_GRATIS_KM      BIGINT,
    CORREIO_KM           BIGINT,
    ASSENTOS             INT,
    PAYLOAD              BIGINT,
    HORAS_VOADAS         FLOAT,
    BAGAGEM_KM           BIGINT,
    CONSTRAINT FK_FATO_VOO_DIM_DATA FOREIGN KEY (ID_DATA)
        REFERENCES DIM_DATA (ID_DATA),
    CONSTRAINT FK_FATO_VOOS_DIM_EMPRESA FOREIGN KEY (ID_EMPRESA)
        REFERENCES DIM_EMPRESA (ID_EMPRESA),
    CONSTRAINT FK_FATO_VOO_DIM_AEROPORTO_ORIGEM FOREIGN KEY (ID_AEROPORTO_ORIGEM)
        REFERENCES DIM_AEROPORTO (ID_AEROPORTO),
    CONSTRAINT FK_FATO_VOOS_DIM_AEROPORTO_DESTINO FOREIGN KEY (ID_AEROPORTO_DESTINO)
        REFERENCES DIM_AEROPORTO (ID_AEROPORTO),
    CONSTRAINT FK_FATO_VOOS_DIM_GRUPO_VOO FOREIGN KEY (ID_GRUPO_VOO)
        REFERENCES DIM_GRUPO_VOO (ID_GRUPO_VOO)
);